version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - API_HOST=${API_HOST}
      - SENDPULSE_WEBHOOK_TOKEN=${SENDPULSE_WEBHOOK_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
